version: '3.8'

services:
  srsepc:
    container_name: virtual-srsepc
    build: .
    command: stdbuf -oL srsepc /etc/srsran/epc.conf --mme.mme_bind_addr=192.168.65.10 --spgw.gtpu_bind_addr=192.168.65.10
    networks:
      corenet:
        ipv4_address: 192.168.65.10
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
  srsran:
    container_name: virtual-srsran
    build: .
    command: tail -F anything
    networks:
      corenet:
        ipv4_address: 192.168.65.11
    ipc: shareable
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun

networks:
  corenet:
    ipam:
      driver: default
      config:
        - subnet: 192.168.65.0/24
