version: '3.8'

x-srsue:
  &ue-settings
  build: .
  command: stdbuf -oL srsue /etc/srsran/ue.conf.fauxrf
  ipc: service:srsenb
  cap_add:
    - NET_ADMIN
    - SYS_NICE
  devices:
    - /dev/net/tun
  depends_on:
    - srsenb

services:
  srsepc:
    container_name: virtual-srsepc
    build: .
    command: stdbuf -oL srsepc /etc/srsran/epc.conf --mme.mme_bind_addr=192.168.65.10 --spgw.gtpu_bind_addr=192.168.65.10
    networks:
      corenet:
        ipv4_address: 192.168.65.10
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
  srsenb:
    container_name: virtual-srsenb
    build: .
    command: srsenb /etc/srsran/enb.conf.fauxrf --enb.mme_addr=192.168.65.10 --enb.gtp_bind_addr=192.168.65.11 --enb.s1c_bind_addr=192.168.65.11 --enb_files.sib_config=/etc/srsran/sib.conf
    networks:
      corenet:
        ipv4_address: 192.168.65.11
    ipc: shareable
    cap_add:
      - SYS_NICE
  srsue:
    << : *ue-settings
    container_name: virtual-srsue
  # srsue2:
  #   << : *ue-settings
  #   container_name: virtual-srsue2
  #   command: "srsue ue.conf.fauxrf --usim.imsi=001010123456780"

networks:
  corenet:
    ipam:
      driver: default
      config:
        - subnet: 192.168.65.0/24
